config/routes.rb
Rails.application.routes.draw do
  root to: 'documents#new'
  get '/', to: 'documents#new'
  get '/uploads', to: 'documents#index'
  get '/file/:id', to: 'documents#show'
  post '/file-upload', to: 'documents#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box_adapter.rb
require 'boxr'

class BoxAdapter < ApplicationRecord
  attr_accessor :client, :items

  def initialize
    @client = Boxr::Client.new
  end


  def send_file(file, name)
    folder = @client.folder_from_path('/')
    @client.upload_file(file, folder, name: name)
    true
  end

  def show_files
    @items = @client.folder_items(Boxr::ROOT)
  end

  def download_file(file)
    @client.download_file(file, version: nil, follow_redirect: true)
  end
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, :last_name, length: { maximum: 50 }, presence: true
  validates :email, length: { maximum: 255 }, presence: true,
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_admin_login, only: [:index, :show]
  before_action :require_user_login, only: [:new, :create]

  def new
    @document = Document.new
  end

  def create
    # create a document object to keep track of all files and times uploaded to Box server
    document = Document.new(filename: params[:file].original_filename)
    if document.save!
      upload(params[:file])
    end
  end

  def index
    @items = client.show_files
  end

  def show
    file = params[:id]
    send_data client.download_file(file)
  end

  private
    def document_params
      params.require(:document).permit(:file)
    end

    def upload(document)
      file = params[:file]
      filename = "#{Date.today}_#{current_user.last_name}_#{current_user.first_name}_#{file.original_filename}"
      if client.send_file(file.tempfile, filename)
        true
      else
        @errors = client.errors.full_message
      end
    end

    def client
      @client ||= BoxAdapter.new
    end

    def require_admin_login
      unless logged_in? && is_admin?
        redirect_to login_path
      end
    end

    def require_user_login
      unless logged_in? && !is_admin?
        redirect_to login_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in? && is_admin?
      redirect_to '/uploads'
    elsif
      logged_in? && !is_admin?
      redirect_to '/'
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to '/uploads'
    else
      @errors = ["Invalid email/password combination"]
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_user, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      if @user.admin?
        redirect_to '/uploads'
      else
        redirect_to '/'
      end
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                  :password_confirmation)
    end

    def require_no_user
      redirect_to uploads_path if logged_in? && is_admin?
      redirect_to root_path if logged_in? && !is_admin?
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_helper.rb
module BoxHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def is_admin?
    current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_messages.html.erb
<div class="s-message hidden" id='success-message'>
  <h1>Successfully uploaded file!</h1>
</div>

<div class="e-message hidden" id='error-message'>
  <h1>You've already sent this file!</h1>
</div>

app/views/documents/index.html.erb
<% if logged_in? && current_user.admin? %>
  <div class="upload-files">
    <div class="title">
      <h1>Click to download file </h1>
    </div>
    <ul class="link-list">
      <% @items.each do |i| %>
          <li class="link"><%= link_to "#{i.name}", controller: "documents", action: "show", id: i.id %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/documents/new.html.erb
<div class="new-form">
  <%= render 'shared/login_errors' %>
  <%= form_for(@document, url: { action: "create" }, html: { multipart: true, class: "dropzone dropzone-custom", id: "doc-dropzone"}) do |f|  %>
  <%= render 'messages' %>
    <div class="fallback">
      <%= f.file_field :document %><br>
      <%= f.submit "Upload" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOALoanApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-light bg-faded">
      <a class="navbar-brand" href="https://www.bankofamerica.com/">
        <%= image_tag("BOA_logo.png", class: "d-inline-block align-top logo") %>
      </a>
      <% if logged_in? %>
        <%= button_to "Logout", logout_path, method: 'delete', class: 'btn btn-primary logout-button' %>
      <% else %>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item ">
            <% unless current_page?(login_path) %>
              <%= link_to "Login", login_path, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item ">
            <% unless current_page?(signup_path) %>
              <%= link_to "Signup", signup_path, class: 'nav-link' %>
            <% end %>
          </li>
        </ul>
      <% end %>
    </nav>
    <div class="background-color">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login_errors.html.erb
<div class="err" %>
  <% if @errors %>
    <% @errors.each do |error| %>
      <li class="error-msg"><%= error %></li>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="login col-xs-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <h1>Sign up</h1>

      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Password confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit "Create Account", class: "btn btn-primary submit-login" %>
      <% end %>
    </div>
  </div>
</div>